# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arch/.config/qypr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arch/.config/qypr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arch/.config/qypr/CMakeFiles /home/arch/.config/qypr//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arch/.config/qypr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/arch/.config/qypr/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qypr-lock

# Build rule for target.
qypr-lock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qypr-lock
.PHONY : qypr-lock

# fast build rule for target.
qypr-lock/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/build
.PHONY : qypr-lock/fast

#=============================================================================
# Target rules for targets named qypr-record

# Build rule for target.
qypr-record: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qypr-record
.PHONY : qypr-record

# fast build rule for target.
qypr-record/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/build
.PHONY : qypr-record/fast

#=============================================================================
# Target rules for targets named qypr-test

# Build rule for target.
qypr-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qypr-test
.PHONY : qypr-test

# fast build rule for target.
qypr-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/build
.PHONY : qypr-test/fast

src/auth/PamAuthenticator.o: src/auth/PamAuthenticator.cpp.o
.PHONY : src/auth/PamAuthenticator.o

# target to build an object file
src/auth/PamAuthenticator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/auth/PamAuthenticator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/auth/PamAuthenticator.cpp.o
.PHONY : src/auth/PamAuthenticator.cpp.o

src/auth/PamAuthenticator.i: src/auth/PamAuthenticator.cpp.i
.PHONY : src/auth/PamAuthenticator.i

# target to preprocess a source file
src/auth/PamAuthenticator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/auth/PamAuthenticator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/auth/PamAuthenticator.cpp.i
.PHONY : src/auth/PamAuthenticator.cpp.i

src/auth/PamAuthenticator.s: src/auth/PamAuthenticator.cpp.s
.PHONY : src/auth/PamAuthenticator.s

# target to generate assembly for a file
src/auth/PamAuthenticator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/auth/PamAuthenticator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/auth/PamAuthenticator.cpp.s
.PHONY : src/auth/PamAuthenticator.cpp.s

src/core/App.o: src/core/App.cpp.o
.PHONY : src/core/App.o

# target to build an object file
src/core/App.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/core/App.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/core/App.cpp.o
.PHONY : src/core/App.cpp.o

src/core/App.i: src/core/App.cpp.i
.PHONY : src/core/App.i

# target to preprocess a source file
src/core/App.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/core/App.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/core/App.cpp.i
.PHONY : src/core/App.cpp.i

src/core/App.s: src/core/App.cpp.s
.PHONY : src/core/App.s

# target to generate assembly for a file
src/core/App.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/core/App.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/core/App.cpp.s
.PHONY : src/core/App.cpp.s

src/core/EventLoop.o: src/core/EventLoop.cpp.o
.PHONY : src/core/EventLoop.o

# target to build an object file
src/core/EventLoop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/core/EventLoop.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/core/EventLoop.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/core/EventLoop.cpp.o
.PHONY : src/core/EventLoop.cpp.o

src/core/EventLoop.i: src/core/EventLoop.cpp.i
.PHONY : src/core/EventLoop.i

# target to preprocess a source file
src/core/EventLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/core/EventLoop.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/core/EventLoop.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/core/EventLoop.cpp.i
.PHONY : src/core/EventLoop.cpp.i

src/core/EventLoop.s: src/core/EventLoop.cpp.s
.PHONY : src/core/EventLoop.s

# target to generate assembly for a file
src/core/EventLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/core/EventLoop.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/core/EventLoop.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/core/EventLoop.cpp.s
.PHONY : src/core/EventLoop.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mpris/MprisController.o: src/mpris/MprisController.cpp.o
.PHONY : src/mpris/MprisController.o

# target to build an object file
src/mpris/MprisController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/mpris/MprisController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/mpris/MprisController.cpp.o
.PHONY : src/mpris/MprisController.cpp.o

src/mpris/MprisController.i: src/mpris/MprisController.cpp.i
.PHONY : src/mpris/MprisController.i

# target to preprocess a source file
src/mpris/MprisController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/mpris/MprisController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/mpris/MprisController.cpp.i
.PHONY : src/mpris/MprisController.cpp.i

src/mpris/MprisController.s: src/mpris/MprisController.cpp.s
.PHONY : src/mpris/MprisController.s

# target to generate assembly for a file
src/mpris/MprisController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/mpris/MprisController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/mpris/MprisController.cpp.s
.PHONY : src/mpris/MprisController.cpp.s

src/notifications/NotificationLog.o: src/notifications/NotificationLog.cpp.o
.PHONY : src/notifications/NotificationLog.o

# target to build an object file
src/notifications/NotificationLog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/notifications/NotificationLog.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/notifications/NotificationLog.cpp.o
.PHONY : src/notifications/NotificationLog.cpp.o

src/notifications/NotificationLog.i: src/notifications/NotificationLog.cpp.i
.PHONY : src/notifications/NotificationLog.i

# target to preprocess a source file
src/notifications/NotificationLog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/notifications/NotificationLog.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/notifications/NotificationLog.cpp.i
.PHONY : src/notifications/NotificationLog.cpp.i

src/notifications/NotificationLog.s: src/notifications/NotificationLog.cpp.s
.PHONY : src/notifications/NotificationLog.s

# target to generate assembly for a file
src/notifications/NotificationLog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/notifications/NotificationLog.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/notifications/NotificationLog.cpp.s
.PHONY : src/notifications/NotificationLog.cpp.s

src/notifications/NotificationMonitor.o: src/notifications/NotificationMonitor.cpp.o
.PHONY : src/notifications/NotificationMonitor.o

# target to build an object file
src/notifications/NotificationMonitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/notifications/NotificationMonitor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/notifications/NotificationMonitor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/notifications/NotificationMonitor.cpp.o
.PHONY : src/notifications/NotificationMonitor.cpp.o

src/notifications/NotificationMonitor.i: src/notifications/NotificationMonitor.cpp.i
.PHONY : src/notifications/NotificationMonitor.i

# target to preprocess a source file
src/notifications/NotificationMonitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/notifications/NotificationMonitor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/notifications/NotificationMonitor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/notifications/NotificationMonitor.cpp.i
.PHONY : src/notifications/NotificationMonitor.cpp.i

src/notifications/NotificationMonitor.s: src/notifications/NotificationMonitor.cpp.s
.PHONY : src/notifications/NotificationMonitor.s

# target to generate assembly for a file
src/notifications/NotificationMonitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/notifications/NotificationMonitor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/notifications/NotificationMonitor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/notifications/NotificationMonitor.cpp.s
.PHONY : src/notifications/NotificationMonitor.cpp.s

src/power/PowerManager.o: src/power/PowerManager.cpp.o
.PHONY : src/power/PowerManager.o

# target to build an object file
src/power/PowerManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/power/PowerManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/power/PowerManager.cpp.o
.PHONY : src/power/PowerManager.cpp.o

src/power/PowerManager.i: src/power/PowerManager.cpp.i
.PHONY : src/power/PowerManager.i

# target to preprocess a source file
src/power/PowerManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/power/PowerManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/power/PowerManager.cpp.i
.PHONY : src/power/PowerManager.cpp.i

src/power/PowerManager.s: src/power/PowerManager.cpp.s
.PHONY : src/power/PowerManager.s

# target to generate assembly for a file
src/power/PowerManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/power/PowerManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/power/PowerManager.cpp.s
.PHONY : src/power/PowerManager.cpp.s

src/recorder_main.o: src/recorder_main.cpp.o
.PHONY : src/recorder_main.o

# target to build an object file
src/recorder_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/recorder_main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/recorder_main.cpp.o
.PHONY : src/recorder_main.cpp.o

src/recorder_main.i: src/recorder_main.cpp.i
.PHONY : src/recorder_main.i

# target to preprocess a source file
src/recorder_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/recorder_main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/recorder_main.cpp.i
.PHONY : src/recorder_main.cpp.i

src/recorder_main.s: src/recorder_main.cpp.s
.PHONY : src/recorder_main.s

# target to generate assembly for a file
src/recorder_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-record.dir/build.make CMakeFiles/qypr-record.dir/src/recorder_main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/recorder_main.cpp.s
.PHONY : src/recorder_main.cpp.s

src/render/Painter.o: src/render/Painter.cpp.o
.PHONY : src/render/Painter.o

# target to build an object file
src/render/Painter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/render/Painter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/render/Painter.cpp.o
.PHONY : src/render/Painter.cpp.o

src/render/Painter.i: src/render/Painter.cpp.i
.PHONY : src/render/Painter.i

# target to preprocess a source file
src/render/Painter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/render/Painter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/render/Painter.cpp.i
.PHONY : src/render/Painter.cpp.i

src/render/Painter.s: src/render/Painter.cpp.s
.PHONY : src/render/Painter.s

# target to generate assembly for a file
src/render/Painter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/render/Painter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/render/Painter.cpp.s
.PHONY : src/render/Painter.cpp.s

src/system/BatteryBackend.o: src/system/BatteryBackend.cpp.o
.PHONY : src/system/BatteryBackend.o

# target to build an object file
src/system/BatteryBackend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/system/BatteryBackend.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/system/BatteryBackend.cpp.o
.PHONY : src/system/BatteryBackend.cpp.o

src/system/BatteryBackend.i: src/system/BatteryBackend.cpp.i
.PHONY : src/system/BatteryBackend.i

# target to preprocess a source file
src/system/BatteryBackend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/system/BatteryBackend.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/system/BatteryBackend.cpp.i
.PHONY : src/system/BatteryBackend.cpp.i

src/system/BatteryBackend.s: src/system/BatteryBackend.cpp.s
.PHONY : src/system/BatteryBackend.s

# target to generate assembly for a file
src/system/BatteryBackend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/system/BatteryBackend.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/system/BatteryBackend.cpp.s
.PHONY : src/system/BatteryBackend.cpp.s

src/system/BrightnessBackend.o: src/system/BrightnessBackend.cpp.o
.PHONY : src/system/BrightnessBackend.o

# target to build an object file
src/system/BrightnessBackend.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/system/BrightnessBackend.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/system/BrightnessBackend.cpp.o
.PHONY : src/system/BrightnessBackend.cpp.o

src/system/BrightnessBackend.i: src/system/BrightnessBackend.cpp.i
.PHONY : src/system/BrightnessBackend.i

# target to preprocess a source file
src/system/BrightnessBackend.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/system/BrightnessBackend.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/system/BrightnessBackend.cpp.i
.PHONY : src/system/BrightnessBackend.cpp.i

src/system/BrightnessBackend.s: src/system/BrightnessBackend.cpp.s
.PHONY : src/system/BrightnessBackend.s

# target to generate assembly for a file
src/system/BrightnessBackend.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/system/BrightnessBackend.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/system/BrightnessBackend.cpp.s
.PHONY : src/system/BrightnessBackend.cpp.s

src/system/SystemBus.o: src/system/SystemBus.cpp.o
.PHONY : src/system/SystemBus.o

# target to build an object file
src/system/SystemBus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/system/SystemBus.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/system/SystemBus.cpp.o
.PHONY : src/system/SystemBus.cpp.o

src/system/SystemBus.i: src/system/SystemBus.cpp.i
.PHONY : src/system/SystemBus.i

# target to preprocess a source file
src/system/SystemBus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/system/SystemBus.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/system/SystemBus.cpp.i
.PHONY : src/system/SystemBus.cpp.i

src/system/SystemBus.s: src/system/SystemBus.cpp.s
.PHONY : src/system/SystemBus.s

# target to generate assembly for a file
src/system/SystemBus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/system/SystemBus.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/system/SystemBus.cpp.s
.PHONY : src/system/SystemBus.cpp.s

src/ui/ActionButton.o: src/ui/ActionButton.cpp.o
.PHONY : src/ui/ActionButton.o

# target to build an object file
src/ui/ActionButton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/ActionButton.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/ActionButton.cpp.o
.PHONY : src/ui/ActionButton.cpp.o

src/ui/ActionButton.i: src/ui/ActionButton.cpp.i
.PHONY : src/ui/ActionButton.i

# target to preprocess a source file
src/ui/ActionButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/ActionButton.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/ActionButton.cpp.i
.PHONY : src/ui/ActionButton.cpp.i

src/ui/ActionButton.s: src/ui/ActionButton.cpp.s
.PHONY : src/ui/ActionButton.s

# target to generate assembly for a file
src/ui/ActionButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/ActionButton.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/ActionButton.cpp.s
.PHONY : src/ui/ActionButton.cpp.s

src/ui/AudioController.o: src/ui/AudioController.cpp.o
.PHONY : src/ui/AudioController.o

# target to build an object file
src/ui/AudioController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/AudioController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/AudioController.cpp.o
.PHONY : src/ui/AudioController.cpp.o

src/ui/AudioController.i: src/ui/AudioController.cpp.i
.PHONY : src/ui/AudioController.i

# target to preprocess a source file
src/ui/AudioController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/AudioController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/AudioController.cpp.i
.PHONY : src/ui/AudioController.cpp.i

src/ui/AudioController.s: src/ui/AudioController.cpp.s
.PHONY : src/ui/AudioController.s

# target to generate assembly for a file
src/ui/AudioController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/AudioController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/AudioController.cpp.s
.PHONY : src/ui/AudioController.cpp.s

src/ui/Clock.o: src/ui/Clock.cpp.o
.PHONY : src/ui/Clock.o

# target to build an object file
src/ui/Clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/Clock.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/Clock.cpp.o
.PHONY : src/ui/Clock.cpp.o

src/ui/Clock.i: src/ui/Clock.cpp.i
.PHONY : src/ui/Clock.i

# target to preprocess a source file
src/ui/Clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/Clock.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/Clock.cpp.i
.PHONY : src/ui/Clock.cpp.i

src/ui/Clock.s: src/ui/Clock.cpp.s
.PHONY : src/ui/Clock.s

# target to generate assembly for a file
src/ui/Clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/Clock.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/Clock.cpp.s
.PHONY : src/ui/Clock.cpp.s

src/ui/IconResolver.o: src/ui/IconResolver.cpp.o
.PHONY : src/ui/IconResolver.o

# target to build an object file
src/ui/IconResolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/IconResolver.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/IconResolver.cpp.o
.PHONY : src/ui/IconResolver.cpp.o

src/ui/IconResolver.i: src/ui/IconResolver.cpp.i
.PHONY : src/ui/IconResolver.i

# target to preprocess a source file
src/ui/IconResolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/IconResolver.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/IconResolver.cpp.i
.PHONY : src/ui/IconResolver.cpp.i

src/ui/IconResolver.s: src/ui/IconResolver.cpp.s
.PHONY : src/ui/IconResolver.s

# target to generate assembly for a file
src/ui/IconResolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/IconResolver.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/IconResolver.cpp.s
.PHONY : src/ui/IconResolver.cpp.s

src/ui/LockScreen.o: src/ui/LockScreen.cpp.o
.PHONY : src/ui/LockScreen.o

# target to build an object file
src/ui/LockScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/LockScreen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/LockScreen.cpp.o
.PHONY : src/ui/LockScreen.cpp.o

src/ui/LockScreen.i: src/ui/LockScreen.cpp.i
.PHONY : src/ui/LockScreen.i

# target to preprocess a source file
src/ui/LockScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/LockScreen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/LockScreen.cpp.i
.PHONY : src/ui/LockScreen.cpp.i

src/ui/LockScreen.s: src/ui/LockScreen.cpp.s
.PHONY : src/ui/LockScreen.s

# target to generate assembly for a file
src/ui/LockScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/LockScreen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/LockScreen.cpp.s
.PHONY : src/ui/LockScreen.cpp.s

src/ui/Notification.o: src/ui/Notification.cpp.o
.PHONY : src/ui/Notification.o

# target to build an object file
src/ui/Notification.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/Notification.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/Notification.cpp.o
.PHONY : src/ui/Notification.cpp.o

src/ui/Notification.i: src/ui/Notification.cpp.i
.PHONY : src/ui/Notification.i

# target to preprocess a source file
src/ui/Notification.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/Notification.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/Notification.cpp.i
.PHONY : src/ui/Notification.cpp.i

src/ui/Notification.s: src/ui/Notification.cpp.s
.PHONY : src/ui/Notification.s

# target to generate assembly for a file
src/ui/Notification.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/Notification.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/Notification.cpp.s
.PHONY : src/ui/Notification.cpp.s

src/ui/PasswordField.o: src/ui/PasswordField.cpp.o
.PHONY : src/ui/PasswordField.o

# target to build an object file
src/ui/PasswordField.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/PasswordField.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/PasswordField.cpp.o
.PHONY : src/ui/PasswordField.cpp.o

src/ui/PasswordField.i: src/ui/PasswordField.cpp.i
.PHONY : src/ui/PasswordField.i

# target to preprocess a source file
src/ui/PasswordField.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/PasswordField.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/PasswordField.cpp.i
.PHONY : src/ui/PasswordField.cpp.i

src/ui/PasswordField.s: src/ui/PasswordField.cpp.s
.PHONY : src/ui/PasswordField.s

# target to generate assembly for a file
src/ui/PasswordField.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/PasswordField.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/PasswordField.cpp.s
.PHONY : src/ui/PasswordField.cpp.s

src/ui/PowerDialog.o: src/ui/PowerDialog.cpp.o
.PHONY : src/ui/PowerDialog.o

# target to build an object file
src/ui/PowerDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/PowerDialog.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/PowerDialog.cpp.o
.PHONY : src/ui/PowerDialog.cpp.o

src/ui/PowerDialog.i: src/ui/PowerDialog.cpp.i
.PHONY : src/ui/PowerDialog.i

# target to preprocess a source file
src/ui/PowerDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/PowerDialog.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/PowerDialog.cpp.i
.PHONY : src/ui/PowerDialog.cpp.i

src/ui/PowerDialog.s: src/ui/PowerDialog.cpp.s
.PHONY : src/ui/PowerDialog.s

# target to generate assembly for a file
src/ui/PowerDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/PowerDialog.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/PowerDialog.cpp.s
.PHONY : src/ui/PowerDialog.cpp.s

src/ui/Shell.o: src/ui/Shell.cpp.o
.PHONY : src/ui/Shell.o

# target to build an object file
src/ui/Shell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/Shell.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/Shell.cpp.o
.PHONY : src/ui/Shell.cpp.o

src/ui/Shell.i: src/ui/Shell.cpp.i
.PHONY : src/ui/Shell.i

# target to preprocess a source file
src/ui/Shell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/Shell.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/Shell.cpp.i
.PHONY : src/ui/Shell.cpp.i

src/ui/Shell.s: src/ui/Shell.cpp.s
.PHONY : src/ui/Shell.s

# target to generate assembly for a file
src/ui/Shell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/Shell.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/Shell.cpp.s
.PHONY : src/ui/Shell.cpp.s

src/ui/StatusMessage.o: src/ui/StatusMessage.cpp.o
.PHONY : src/ui/StatusMessage.o

# target to build an object file
src/ui/StatusMessage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/StatusMessage.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/StatusMessage.cpp.o
.PHONY : src/ui/StatusMessage.cpp.o

src/ui/StatusMessage.i: src/ui/StatusMessage.cpp.i
.PHONY : src/ui/StatusMessage.i

# target to preprocess a source file
src/ui/StatusMessage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/StatusMessage.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/StatusMessage.cpp.i
.PHONY : src/ui/StatusMessage.cpp.i

src/ui/StatusMessage.s: src/ui/StatusMessage.cpp.s
.PHONY : src/ui/StatusMessage.s

# target to generate assembly for a file
src/ui/StatusMessage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/StatusMessage.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/StatusMessage.cpp.s
.PHONY : src/ui/StatusMessage.cpp.s

src/ui/indicators/BatteryIndicator.o: src/ui/indicators/BatteryIndicator.cpp.o
.PHONY : src/ui/indicators/BatteryIndicator.o

# target to build an object file
src/ui/indicators/BatteryIndicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/indicators/BatteryIndicator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/indicators/BatteryIndicator.cpp.o
.PHONY : src/ui/indicators/BatteryIndicator.cpp.o

src/ui/indicators/BatteryIndicator.i: src/ui/indicators/BatteryIndicator.cpp.i
.PHONY : src/ui/indicators/BatteryIndicator.i

# target to preprocess a source file
src/ui/indicators/BatteryIndicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/indicators/BatteryIndicator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/indicators/BatteryIndicator.cpp.i
.PHONY : src/ui/indicators/BatteryIndicator.cpp.i

src/ui/indicators/BatteryIndicator.s: src/ui/indicators/BatteryIndicator.cpp.s
.PHONY : src/ui/indicators/BatteryIndicator.s

# target to generate assembly for a file
src/ui/indicators/BatteryIndicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/indicators/BatteryIndicator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/indicators/BatteryIndicator.cpp.s
.PHONY : src/ui/indicators/BatteryIndicator.cpp.s

src/ui/indicators/BrightnessIndicator.o: src/ui/indicators/BrightnessIndicator.cpp.o
.PHONY : src/ui/indicators/BrightnessIndicator.o

# target to build an object file
src/ui/indicators/BrightnessIndicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/indicators/BrightnessIndicator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/indicators/BrightnessIndicator.cpp.o
.PHONY : src/ui/indicators/BrightnessIndicator.cpp.o

src/ui/indicators/BrightnessIndicator.i: src/ui/indicators/BrightnessIndicator.cpp.i
.PHONY : src/ui/indicators/BrightnessIndicator.i

# target to preprocess a source file
src/ui/indicators/BrightnessIndicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/indicators/BrightnessIndicator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/indicators/BrightnessIndicator.cpp.i
.PHONY : src/ui/indicators/BrightnessIndicator.cpp.i

src/ui/indicators/BrightnessIndicator.s: src/ui/indicators/BrightnessIndicator.cpp.s
.PHONY : src/ui/indicators/BrightnessIndicator.s

# target to generate assembly for a file
src/ui/indicators/BrightnessIndicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/indicators/BrightnessIndicator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/indicators/BrightnessIndicator.cpp.s
.PHONY : src/ui/indicators/BrightnessIndicator.cpp.s

src/ui/indicators/ClockIndicator.o: src/ui/indicators/ClockIndicator.cpp.o
.PHONY : src/ui/indicators/ClockIndicator.o

# target to build an object file
src/ui/indicators/ClockIndicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/indicators/ClockIndicator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/indicators/ClockIndicator.cpp.o
.PHONY : src/ui/indicators/ClockIndicator.cpp.o

src/ui/indicators/ClockIndicator.i: src/ui/indicators/ClockIndicator.cpp.i
.PHONY : src/ui/indicators/ClockIndicator.i

# target to preprocess a source file
src/ui/indicators/ClockIndicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/indicators/ClockIndicator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/indicators/ClockIndicator.cpp.i
.PHONY : src/ui/indicators/ClockIndicator.cpp.i

src/ui/indicators/ClockIndicator.s: src/ui/indicators/ClockIndicator.cpp.s
.PHONY : src/ui/indicators/ClockIndicator.s

# target to generate assembly for a file
src/ui/indicators/ClockIndicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/indicators/ClockIndicator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/indicators/ClockIndicator.cpp.s
.PHONY : src/ui/indicators/ClockIndicator.cpp.s

src/ui/statusbar/IndicatorRegistry.o: src/ui/statusbar/IndicatorRegistry.cpp.o
.PHONY : src/ui/statusbar/IndicatorRegistry.o

# target to build an object file
src/ui/statusbar/IndicatorRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/IndicatorRegistry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/IndicatorRegistry.cpp.o
.PHONY : src/ui/statusbar/IndicatorRegistry.cpp.o

src/ui/statusbar/IndicatorRegistry.i: src/ui/statusbar/IndicatorRegistry.cpp.i
.PHONY : src/ui/statusbar/IndicatorRegistry.i

# target to preprocess a source file
src/ui/statusbar/IndicatorRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/IndicatorRegistry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/IndicatorRegistry.cpp.i
.PHONY : src/ui/statusbar/IndicatorRegistry.cpp.i

src/ui/statusbar/IndicatorRegistry.s: src/ui/statusbar/IndicatorRegistry.cpp.s
.PHONY : src/ui/statusbar/IndicatorRegistry.s

# target to generate assembly for a file
src/ui/statusbar/IndicatorRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/IndicatorRegistry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/IndicatorRegistry.cpp.s
.PHONY : src/ui/statusbar/IndicatorRegistry.cpp.s

src/ui/statusbar/PopoverManager.o: src/ui/statusbar/PopoverManager.cpp.o
.PHONY : src/ui/statusbar/PopoverManager.o

# target to build an object file
src/ui/statusbar/PopoverManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/PopoverManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/PopoverManager.cpp.o
.PHONY : src/ui/statusbar/PopoverManager.cpp.o

src/ui/statusbar/PopoverManager.i: src/ui/statusbar/PopoverManager.cpp.i
.PHONY : src/ui/statusbar/PopoverManager.i

# target to preprocess a source file
src/ui/statusbar/PopoverManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/PopoverManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/PopoverManager.cpp.i
.PHONY : src/ui/statusbar/PopoverManager.cpp.i

src/ui/statusbar/PopoverManager.s: src/ui/statusbar/PopoverManager.cpp.s
.PHONY : src/ui/statusbar/PopoverManager.s

# target to generate assembly for a file
src/ui/statusbar/PopoverManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/PopoverManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/PopoverManager.cpp.s
.PHONY : src/ui/statusbar/PopoverManager.cpp.s

src/ui/statusbar/QSTile.o: src/ui/statusbar/QSTile.cpp.o
.PHONY : src/ui/statusbar/QSTile.o

# target to build an object file
src/ui/statusbar/QSTile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/QSTile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/QSTile.cpp.o
.PHONY : src/ui/statusbar/QSTile.cpp.o

src/ui/statusbar/QSTile.i: src/ui/statusbar/QSTile.cpp.i
.PHONY : src/ui/statusbar/QSTile.i

# target to preprocess a source file
src/ui/statusbar/QSTile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/QSTile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/QSTile.cpp.i
.PHONY : src/ui/statusbar/QSTile.cpp.i

src/ui/statusbar/QSTile.s: src/ui/statusbar/QSTile.cpp.s
.PHONY : src/ui/statusbar/QSTile.s

# target to generate assembly for a file
src/ui/statusbar/QSTile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/QSTile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/QSTile.cpp.s
.PHONY : src/ui/statusbar/QSTile.cpp.s

src/ui/statusbar/QuickSettingsPanel.o: src/ui/statusbar/QuickSettingsPanel.cpp.o
.PHONY : src/ui/statusbar/QuickSettingsPanel.o

# target to build an object file
src/ui/statusbar/QuickSettingsPanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/QuickSettingsPanel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/QuickSettingsPanel.cpp.o
.PHONY : src/ui/statusbar/QuickSettingsPanel.cpp.o

src/ui/statusbar/QuickSettingsPanel.i: src/ui/statusbar/QuickSettingsPanel.cpp.i
.PHONY : src/ui/statusbar/QuickSettingsPanel.i

# target to preprocess a source file
src/ui/statusbar/QuickSettingsPanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/QuickSettingsPanel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/QuickSettingsPanel.cpp.i
.PHONY : src/ui/statusbar/QuickSettingsPanel.cpp.i

src/ui/statusbar/QuickSettingsPanel.s: src/ui/statusbar/QuickSettingsPanel.cpp.s
.PHONY : src/ui/statusbar/QuickSettingsPanel.s

# target to generate assembly for a file
src/ui/statusbar/QuickSettingsPanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/QuickSettingsPanel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/QuickSettingsPanel.cpp.s
.PHONY : src/ui/statusbar/QuickSettingsPanel.cpp.s

src/ui/statusbar/StatusBar.o: src/ui/statusbar/StatusBar.cpp.o
.PHONY : src/ui/statusbar/StatusBar.o

# target to build an object file
src/ui/statusbar/StatusBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/StatusBar.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/StatusBar.cpp.o
.PHONY : src/ui/statusbar/StatusBar.cpp.o

src/ui/statusbar/StatusBar.i: src/ui/statusbar/StatusBar.cpp.i
.PHONY : src/ui/statusbar/StatusBar.i

# target to preprocess a source file
src/ui/statusbar/StatusBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/StatusBar.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/StatusBar.cpp.i
.PHONY : src/ui/statusbar/StatusBar.cpp.i

src/ui/statusbar/StatusBar.s: src/ui/statusbar/StatusBar.cpp.s
.PHONY : src/ui/statusbar/StatusBar.s

# target to generate assembly for a file
src/ui/statusbar/StatusBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/StatusBar.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/StatusBar.cpp.s
.PHONY : src/ui/statusbar/StatusBar.cpp.s

src/ui/statusbar/StatusIndicator.o: src/ui/statusbar/StatusIndicator.cpp.o
.PHONY : src/ui/statusbar/StatusIndicator.o

# target to build an object file
src/ui/statusbar/StatusIndicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/StatusIndicator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/StatusIndicator.cpp.o
.PHONY : src/ui/statusbar/StatusIndicator.cpp.o

src/ui/statusbar/StatusIndicator.i: src/ui/statusbar/StatusIndicator.cpp.i
.PHONY : src/ui/statusbar/StatusIndicator.i

# target to preprocess a source file
src/ui/statusbar/StatusIndicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/StatusIndicator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/StatusIndicator.cpp.i
.PHONY : src/ui/statusbar/StatusIndicator.cpp.i

src/ui/statusbar/StatusIndicator.s: src/ui/statusbar/StatusIndicator.cpp.s
.PHONY : src/ui/statusbar/StatusIndicator.s

# target to generate assembly for a file
src/ui/statusbar/StatusIndicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/ui/statusbar/StatusIndicator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/ui/statusbar/StatusIndicator.cpp.s
.PHONY : src/ui/statusbar/StatusIndicator.cpp.s

src/video/VideoPlayer.o: src/video/VideoPlayer.cpp.o
.PHONY : src/video/VideoPlayer.o

# target to build an object file
src/video/VideoPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/video/VideoPlayer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/video/VideoPlayer.cpp.o
.PHONY : src/video/VideoPlayer.cpp.o

src/video/VideoPlayer.i: src/video/VideoPlayer.cpp.i
.PHONY : src/video/VideoPlayer.i

# target to preprocess a source file
src/video/VideoPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/video/VideoPlayer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/video/VideoPlayer.cpp.i
.PHONY : src/video/VideoPlayer.cpp.i

src/video/VideoPlayer.s: src/video/VideoPlayer.cpp.s
.PHONY : src/video/VideoPlayer.s

# target to generate assembly for a file
src/video/VideoPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/video/VideoPlayer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/video/VideoPlayer.cpp.s
.PHONY : src/video/VideoPlayer.cpp.s

src/wayland/Cursor.o: src/wayland/Cursor.cpp.o
.PHONY : src/wayland/Cursor.o

# target to build an object file
src/wayland/Cursor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/Cursor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/Cursor.cpp.o
.PHONY : src/wayland/Cursor.cpp.o

src/wayland/Cursor.i: src/wayland/Cursor.cpp.i
.PHONY : src/wayland/Cursor.i

# target to preprocess a source file
src/wayland/Cursor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/Cursor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/Cursor.cpp.i
.PHONY : src/wayland/Cursor.cpp.i

src/wayland/Cursor.s: src/wayland/Cursor.cpp.s
.PHONY : src/wayland/Cursor.s

# target to generate assembly for a file
src/wayland/Cursor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/Cursor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/Cursor.cpp.s
.PHONY : src/wayland/Cursor.cpp.s

src/wayland/LockSession.o: src/wayland/LockSession.cpp.o
.PHONY : src/wayland/LockSession.o

# target to build an object file
src/wayland/LockSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/LockSession.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/LockSession.cpp.o
.PHONY : src/wayland/LockSession.cpp.o

src/wayland/LockSession.i: src/wayland/LockSession.cpp.i
.PHONY : src/wayland/LockSession.i

# target to preprocess a source file
src/wayland/LockSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/LockSession.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/LockSession.cpp.i
.PHONY : src/wayland/LockSession.cpp.i

src/wayland/LockSession.s: src/wayland/LockSession.cpp.s
.PHONY : src/wayland/LockSession.s

# target to generate assembly for a file
src/wayland/LockSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/LockSession.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/LockSession.cpp.s
.PHONY : src/wayland/LockSession.cpp.s

src/wayland/Output.o: src/wayland/Output.cpp.o
.PHONY : src/wayland/Output.o

# target to build an object file
src/wayland/Output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/Output.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/Output.cpp.o
.PHONY : src/wayland/Output.cpp.o

src/wayland/Output.i: src/wayland/Output.cpp.i
.PHONY : src/wayland/Output.i

# target to preprocess a source file
src/wayland/Output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/Output.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/Output.cpp.i
.PHONY : src/wayland/Output.cpp.i

src/wayland/Output.s: src/wayland/Output.cpp.s
.PHONY : src/wayland/Output.s

# target to generate assembly for a file
src/wayland/Output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/Output.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/Output.cpp.s
.PHONY : src/wayland/Output.cpp.s

src/wayland/Seat.o: src/wayland/Seat.cpp.o
.PHONY : src/wayland/Seat.o

# target to build an object file
src/wayland/Seat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/Seat.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/Seat.cpp.o
.PHONY : src/wayland/Seat.cpp.o

src/wayland/Seat.i: src/wayland/Seat.cpp.i
.PHONY : src/wayland/Seat.i

# target to preprocess a source file
src/wayland/Seat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/Seat.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/Seat.cpp.i
.PHONY : src/wayland/Seat.cpp.i

src/wayland/Seat.s: src/wayland/Seat.cpp.s
.PHONY : src/wayland/Seat.s

# target to generate assembly for a file
src/wayland/Seat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/Seat.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/Seat.cpp.s
.PHONY : src/wayland/Seat.cpp.s

src/wayland/ShmBuffer.o: src/wayland/ShmBuffer.cpp.o
.PHONY : src/wayland/ShmBuffer.o

# target to build an object file
src/wayland/ShmBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/ShmBuffer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/ShmBuffer.cpp.o
.PHONY : src/wayland/ShmBuffer.cpp.o

src/wayland/ShmBuffer.i: src/wayland/ShmBuffer.cpp.i
.PHONY : src/wayland/ShmBuffer.i

# target to preprocess a source file
src/wayland/ShmBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/ShmBuffer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/ShmBuffer.cpp.i
.PHONY : src/wayland/ShmBuffer.cpp.i

src/wayland/ShmBuffer.s: src/wayland/ShmBuffer.cpp.s
.PHONY : src/wayland/ShmBuffer.s

# target to generate assembly for a file
src/wayland/ShmBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/ShmBuffer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/ShmBuffer.cpp.s
.PHONY : src/wayland/ShmBuffer.cpp.s

src/wayland/WaylandDisplay.o: src/wayland/WaylandDisplay.cpp.o
.PHONY : src/wayland/WaylandDisplay.o

# target to build an object file
src/wayland/WaylandDisplay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/WaylandDisplay.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/WaylandDisplay.cpp.o
.PHONY : src/wayland/WaylandDisplay.cpp.o

src/wayland/WaylandDisplay.i: src/wayland/WaylandDisplay.cpp.i
.PHONY : src/wayland/WaylandDisplay.i

# target to preprocess a source file
src/wayland/WaylandDisplay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/WaylandDisplay.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/WaylandDisplay.cpp.i
.PHONY : src/wayland/WaylandDisplay.cpp.i

src/wayland/WaylandDisplay.s: src/wayland/WaylandDisplay.cpp.s
.PHONY : src/wayland/WaylandDisplay.s

# target to generate assembly for a file
src/wayland/WaylandDisplay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/src/wayland/WaylandDisplay.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/src/wayland/WaylandDisplay.cpp.s
.PHONY : src/wayland/WaylandDisplay.cpp.s

tests/mocks.o: tests/mocks.cpp.o
.PHONY : tests/mocks.o

# target to build an object file
tests/mocks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/tests/mocks.cpp.o
.PHONY : tests/mocks.cpp.o

tests/mocks.i: tests/mocks.cpp.i
.PHONY : tests/mocks.i

# target to preprocess a source file
tests/mocks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/tests/mocks.cpp.i
.PHONY : tests/mocks.cpp.i

tests/mocks.s: tests/mocks.cpp.s
.PHONY : tests/mocks.s

# target to generate assembly for a file
tests/mocks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/tests/mocks.cpp.s
.PHONY : tests/mocks.cpp.s

tests/unit_tests.o: tests/unit_tests.cpp.o
.PHONY : tests/unit_tests.o

# target to build an object file
tests/unit_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/tests/unit_tests.cpp.o
.PHONY : tests/unit_tests.cpp.o

tests/unit_tests.i: tests/unit_tests.cpp.i
.PHONY : tests/unit_tests.i

# target to preprocess a source file
tests/unit_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/tests/unit_tests.cpp.i
.PHONY : tests/unit_tests.cpp.i

tests/unit_tests.s: tests/unit_tests.cpp.s
.PHONY : tests/unit_tests.s

# target to generate assembly for a file
tests/unit_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/tests/unit_tests.cpp.s
.PHONY : tests/unit_tests.cpp.s

wayland-generated/ext-session-lock-v1-protocol.o: wayland-generated/ext-session-lock-v1-protocol.c.o
.PHONY : wayland-generated/ext-session-lock-v1-protocol.o

# target to build an object file
wayland-generated/ext-session-lock-v1-protocol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/wayland-generated/ext-session-lock-v1-protocol.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/wayland-generated/ext-session-lock-v1-protocol.c.o
.PHONY : wayland-generated/ext-session-lock-v1-protocol.c.o

wayland-generated/ext-session-lock-v1-protocol.i: wayland-generated/ext-session-lock-v1-protocol.c.i
.PHONY : wayland-generated/ext-session-lock-v1-protocol.i

# target to preprocess a source file
wayland-generated/ext-session-lock-v1-protocol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/wayland-generated/ext-session-lock-v1-protocol.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/wayland-generated/ext-session-lock-v1-protocol.c.i
.PHONY : wayland-generated/ext-session-lock-v1-protocol.c.i

wayland-generated/ext-session-lock-v1-protocol.s: wayland-generated/ext-session-lock-v1-protocol.c.s
.PHONY : wayland-generated/ext-session-lock-v1-protocol.s

# target to generate assembly for a file
wayland-generated/ext-session-lock-v1-protocol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-lock.dir/build.make CMakeFiles/qypr-lock.dir/wayland-generated/ext-session-lock-v1-protocol.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qypr-test.dir/build.make CMakeFiles/qypr-test.dir/wayland-generated/ext-session-lock-v1-protocol.c.s
.PHONY : wayland-generated/ext-session-lock-v1-protocol.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... qypr-lock"
	@echo "... qypr-record"
	@echo "... qypr-test"
	@echo "... src/auth/PamAuthenticator.o"
	@echo "... src/auth/PamAuthenticator.i"
	@echo "... src/auth/PamAuthenticator.s"
	@echo "... src/core/App.o"
	@echo "... src/core/App.i"
	@echo "... src/core/App.s"
	@echo "... src/core/EventLoop.o"
	@echo "... src/core/EventLoop.i"
	@echo "... src/core/EventLoop.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mpris/MprisController.o"
	@echo "... src/mpris/MprisController.i"
	@echo "... src/mpris/MprisController.s"
	@echo "... src/notifications/NotificationLog.o"
	@echo "... src/notifications/NotificationLog.i"
	@echo "... src/notifications/NotificationLog.s"
	@echo "... src/notifications/NotificationMonitor.o"
	@echo "... src/notifications/NotificationMonitor.i"
	@echo "... src/notifications/NotificationMonitor.s"
	@echo "... src/power/PowerManager.o"
	@echo "... src/power/PowerManager.i"
	@echo "... src/power/PowerManager.s"
	@echo "... src/recorder_main.o"
	@echo "... src/recorder_main.i"
	@echo "... src/recorder_main.s"
	@echo "... src/render/Painter.o"
	@echo "... src/render/Painter.i"
	@echo "... src/render/Painter.s"
	@echo "... src/system/BatteryBackend.o"
	@echo "... src/system/BatteryBackend.i"
	@echo "... src/system/BatteryBackend.s"
	@echo "... src/system/BrightnessBackend.o"
	@echo "... src/system/BrightnessBackend.i"
	@echo "... src/system/BrightnessBackend.s"
	@echo "... src/system/SystemBus.o"
	@echo "... src/system/SystemBus.i"
	@echo "... src/system/SystemBus.s"
	@echo "... src/ui/ActionButton.o"
	@echo "... src/ui/ActionButton.i"
	@echo "... src/ui/ActionButton.s"
	@echo "... src/ui/AudioController.o"
	@echo "... src/ui/AudioController.i"
	@echo "... src/ui/AudioController.s"
	@echo "... src/ui/Clock.o"
	@echo "... src/ui/Clock.i"
	@echo "... src/ui/Clock.s"
	@echo "... src/ui/IconResolver.o"
	@echo "... src/ui/IconResolver.i"
	@echo "... src/ui/IconResolver.s"
	@echo "... src/ui/LockScreen.o"
	@echo "... src/ui/LockScreen.i"
	@echo "... src/ui/LockScreen.s"
	@echo "... src/ui/Notification.o"
	@echo "... src/ui/Notification.i"
	@echo "... src/ui/Notification.s"
	@echo "... src/ui/PasswordField.o"
	@echo "... src/ui/PasswordField.i"
	@echo "... src/ui/PasswordField.s"
	@echo "... src/ui/PowerDialog.o"
	@echo "... src/ui/PowerDialog.i"
	@echo "... src/ui/PowerDialog.s"
	@echo "... src/ui/Shell.o"
	@echo "... src/ui/Shell.i"
	@echo "... src/ui/Shell.s"
	@echo "... src/ui/StatusMessage.o"
	@echo "... src/ui/StatusMessage.i"
	@echo "... src/ui/StatusMessage.s"
	@echo "... src/ui/indicators/BatteryIndicator.o"
	@echo "... src/ui/indicators/BatteryIndicator.i"
	@echo "... src/ui/indicators/BatteryIndicator.s"
	@echo "... src/ui/indicators/BrightnessIndicator.o"
	@echo "... src/ui/indicators/BrightnessIndicator.i"
	@echo "... src/ui/indicators/BrightnessIndicator.s"
	@echo "... src/ui/indicators/ClockIndicator.o"
	@echo "... src/ui/indicators/ClockIndicator.i"
	@echo "... src/ui/indicators/ClockIndicator.s"
	@echo "... src/ui/statusbar/IndicatorRegistry.o"
	@echo "... src/ui/statusbar/IndicatorRegistry.i"
	@echo "... src/ui/statusbar/IndicatorRegistry.s"
	@echo "... src/ui/statusbar/PopoverManager.o"
	@echo "... src/ui/statusbar/PopoverManager.i"
	@echo "... src/ui/statusbar/PopoverManager.s"
	@echo "... src/ui/statusbar/QSTile.o"
	@echo "... src/ui/statusbar/QSTile.i"
	@echo "... src/ui/statusbar/QSTile.s"
	@echo "... src/ui/statusbar/QuickSettingsPanel.o"
	@echo "... src/ui/statusbar/QuickSettingsPanel.i"
	@echo "... src/ui/statusbar/QuickSettingsPanel.s"
	@echo "... src/ui/statusbar/StatusBar.o"
	@echo "... src/ui/statusbar/StatusBar.i"
	@echo "... src/ui/statusbar/StatusBar.s"
	@echo "... src/ui/statusbar/StatusIndicator.o"
	@echo "... src/ui/statusbar/StatusIndicator.i"
	@echo "... src/ui/statusbar/StatusIndicator.s"
	@echo "... src/video/VideoPlayer.o"
	@echo "... src/video/VideoPlayer.i"
	@echo "... src/video/VideoPlayer.s"
	@echo "... src/wayland/Cursor.o"
	@echo "... src/wayland/Cursor.i"
	@echo "... src/wayland/Cursor.s"
	@echo "... src/wayland/LockSession.o"
	@echo "... src/wayland/LockSession.i"
	@echo "... src/wayland/LockSession.s"
	@echo "... src/wayland/Output.o"
	@echo "... src/wayland/Output.i"
	@echo "... src/wayland/Output.s"
	@echo "... src/wayland/Seat.o"
	@echo "... src/wayland/Seat.i"
	@echo "... src/wayland/Seat.s"
	@echo "... src/wayland/ShmBuffer.o"
	@echo "... src/wayland/ShmBuffer.i"
	@echo "... src/wayland/ShmBuffer.s"
	@echo "... src/wayland/WaylandDisplay.o"
	@echo "... src/wayland/WaylandDisplay.i"
	@echo "... src/wayland/WaylandDisplay.s"
	@echo "... tests/mocks.o"
	@echo "... tests/mocks.i"
	@echo "... tests/mocks.s"
	@echo "... tests/unit_tests.o"
	@echo "... tests/unit_tests.i"
	@echo "... tests/unit_tests.s"
	@echo "... wayland-generated/ext-session-lock-v1-protocol.o"
	@echo "... wayland-generated/ext-session-lock-v1-protocol.i"
	@echo "... wayland-generated/ext-session-lock-v1-protocol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/arch/.config/qypr/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

